---
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.6-node
      - image: postgres:9.6
        environment:
          POSTGRES_DATABASE: auto_bisect_poc_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    environment:
      RAILS_ENV: test
    parameters:
      rspec_seed_arg:
        type: string
        default: ''
    steps:
      - checkout
      - run: gem install bundler:1.17.3
      - run: bundle install --path vendor/bundle
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:create
      - run: bundle exec rspec << parameters.rspec_seed_arg >>
