---
version: 2.1

parameters:
  tshoot_rspec:
    type: boolean
    default: false
  tshoot_options:
    type: string
    default: '--seed 1 --bisect'

jobs:
  run_rspec:
    docker:
      - image: cimg/ruby:2.6.6-node
      - image: postgres:9.6
        environment:
          POSTGRES_DATABASE: auto_bisect_poc_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - run: gem install bundler:1.17.3
      - restore_cache:
          name: Restore bundle cache
          key: auto-bisect-poc-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          name: Store bundle cache
          key: auto-bisect-poc-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:create
      - run: bundle exec rspec
  run_rspec_with_tshoot_options:
    docker:
      - image: cimg/ruby:2.6.6-node
      - image: postgres:9.6
        environment:
          POSTGRES_DATABASE: auto_bisect_poc_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - run: gem install bundler:1.17.3
      - run: bundle install --path vendor/bundle
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:create
      - run: bundle exec rspec << pipeline.parameters.tshoot_options >>

workflows:
  rspec:
    unless: << pipeline.parameters.tshoot_rspec >>
    jobs:
      - run_rspec
  rspec_with_tshoot_options:
    when: << pipeline.parameters.tshoot_rspec >>
    jobs:
      - run_rspec_with_tshoot_options
