version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.6-node
      - image: postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - run: gem install bundler:1.17.3
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec

