version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.6-node
      - image: postgres:9.6
        environment:
          POSTGRES_DATABASE: auto_bisect_poc_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    environment:
      RAILS_ENV: test
    parameters:
      rspec_defaults:
        type: boolean
        default: true
      rspec_seed_option:
        type: boolean
        default: false
      rspec_seed_number:
        type: integer
        default: 1
    steps:
      - when:
          condition:
            equal: [<< parameters.rspec_defaults >>, true]
          steps:
            - checkout
            - run: gem install bundler:1.17.3
            - run: bundle install --path vendor/bundle
            - run: bundle exec rake db:create
            - run: bundle exec rspec
      - when:
          condition:
            equal: [<< parameters.rspec_seed_option >>, true]
          steps:
            - checkout
            - run: gem install bundler:1.17.3
            - run: bundle install --path vendor/bundle
            - run: bundle exec rake db:create
            - run: bundle exec rspec --seed << parameters.rspec_seed_number >>

